name: docs

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Doxygen
        run: sudo apt-get install -y doxygen graphviz
      - name: Build documentation
        run: doxygen Doxyfile
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
